### ISSUE TITLE
4.7.15 backtrace on activity details report

### ISSUE THREAD

**Issue by lunarstack1** [mlutfy/ca.bidon.civiexportexcel#6]
When running activity report, then exporting to excel, the following error is displayed. Recreating the same activity details report on 4.7.15, with same search parameters, results in the same back track error. 

Running CiviCRM 4.7.15.

The stack trace:

```backTrace

#0 /public_html/sites/all/modules/civicrm/CRM/Core/Error.php(187): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /public_html/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func((Array:2), Object(DB_Error))
#3 /public_html/sites/all/modules/civicrm/packages/DB.php(985): PEAR_Error->__construct("DB Error: syntax error", -2, 16, (Array:2), "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#4 /public_html/sites/all/modules/civicrm/packages/PEAR.php(575): DB_Error->__construct(-2, 16, (Array:2), "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#5 [internal function](): PEAR->_raiseError(Object(DB_mysqli), NULL, -2, NULL, NULL, "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", "DB_Error", TRUE)
#6 /public_html/sites/all/modules/civicrm/packages/PEAR.php(224): call_user_func_array((Array:2), (Array:8))
#7 /public_html/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->__call("raiseError", (Array:7))
#8 /public_html/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -2, NULL, NULL, "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", "DB_Error", TRUE)
#9 /public_html/sites/all/modules/civicrm/packages/DB/mysqli.php(933): DB_common->raiseError(-2, NULL, NULL, NULL, "1064 ** You have an error in your SQL syntax; check the manual that correspon...")
#10 /public_html/sites/all/modules/civicrm/packages/DB/mysqli.php(403): DB_mysqli->mysqliRaiseError()
#11 /public_html/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysqli->simpleQuery("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#12 /public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(2438): DB_common->query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#13 /public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(1627): DB_DataObject->_query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#14 /public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(354): DB_DataObject->query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#15 /public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(1297): CRM_Core_DAO->query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", TRUE)
#16 /public_html/sites/all/modules/civicrm/CRM/Report/Form.php(2801): CRM_Core_DAO::executeQuery("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#17 /public_html/sites/all/civicrm/civiext/ca.bidon.civiexportexcel/civiexportexcel.php(118): CRM_Report_Form->buildRows("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", (Array:0))
#18 /public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(228): civiexportexcel_civicrm_buildForm("CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity))
#19 /public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:134), "civicrm_buildForm", 2, "CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity), NULL, NULL, NULL, NULL)
#20 /public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(384): CRM_Utils_Hook_DrupalBase->invoke(2, "CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity), NULL, NULL, NULL, NULL, "civicrm_buildForm")
#21 /public_html/sites/all/modules/civicrm/CRM/Core/Form.php(564): CRM_Utils_Hook::buildForm("CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity))
#22 /public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Submit.php(61): CRM_Core_Form->buildForm()
#23 /public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Submit->perform(Object(CRM_Report_Form_Activity), "submit")
#24 /public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Report_Form_Activity), "submit")
#25 /public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("submit")
#26 /public_html/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(113): CRM_Core_Controller->run()
#27 /public_html/sites/all/modules/civicrm/CRM/Report/Page/Instance.php(89): CRM_Utils_Wrapper->run("CRM_Report_Form_Activity", NULL, NULL)
#28 /public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(310): CRM_Report_Page_Instance->run((Array:4), NULL)
#29 /public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#30 /public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#31 /public_html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:4))
#32 [internal function](): civicrm_invoke("report", "instance", "3")
#33 /public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#34 /public_html/index.php(21): menu_execute_active_handler()
#35 {main}
```

When trying to debug the actual SQL query, there are no FROM clauses

```
SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee, civicrm_contact_target.sort_name as civicrm_contact_contact_target, civicrm_contact_source.id as civicrm_contact_contact_source_id, civicrm_contact_assignee.id as civicrm_contact_contact_assignee_id, civicrm_contact_target.id as civicrm_contact_contact_target_id, activity_civireport.id as civicrm_activity_id, activity_civireport.source_record_id as civicrm_activity_source_record_id, activity_civireport.activity_type_id as civicrm_activity_activity_type_id, activity_civireport.subject as civicrm_activity_activity_subject, activity_civireport.activity_date_time as civicrm_activity_activity_date_time, activity_civireport.status_id as civicrm_activity_status_id, activity_civireport.duration as civicrm_activity_duration, activity_civireport.details as civicrm_activity_details, address_civireport.country_id as civicrm_address_country_id LEFT JOIN civicrm_address address_civireport ON (contact_civireport.id = address_civireport.contact_id) AND address_civireport.is_primary = 1 WHERE activity_civireport.is_test = 0 AND activity_civireport.is_deleted = 0 AND activity_civireport.is_current_revision = 1 AND ( activity_date_time >= 20170101000000 ) AND ( activity_date_time <= 20170131235959 ) AND ( activity_civireport.activity_type_id IN (202, 184, 182) ) GROUP BY activity_civireport.id ORDER BY civicrm_activity_activity_date_time ASC, field(civicrm_activity_activity_type_id, 193, 206, 27, 98, 179, 205, 173, 20, 171, 106, 19, 37, 66, 33, 18, 16, 26, 15, 152, 155, 192, 208, 148, 100, 168, 167, 169, 149, 80, 78, 144, 174, 202, 191, 189, 89, 6, 121, 178, 41, 187, 184, 122, 3, 188, 92, 170, 172, 5, 199, 120, 190, 201, 203, 204, 14, 185, 84, 12, 126, 125, 113, 196, 194, 200, 25, 34, 1, 23, 108, 85, 99, 175, 13, 183, 4, 150, 181, 2, 86, 10, 11, 182, 22, 90, 24, 141, 151, 40, 186, 21, 177, 127, 79, 180, 75, 143, 197, 198, 207, 9, 118, 162, 161, 39, 38, 176, 159, 166, 160, 195, 164, 165, 163) ASC
```

**Comment by ilopata1** [comment]
I have the same issue on a 4.7.3 site:

<pre>
backTrace

#0 /var/www/html/sites/all/modules/civicrm/CRM/Core/Error.php(182): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/html/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /var/www/html/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: syntax error", -2, 16, (Array:2), "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#4 /var/www/html/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-2, 16, (Array:2), "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#5 /var/www/html/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -2, NULL, NULL, "SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", "DB_Error", TRUE)
#6 /var/www/html/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-2, NULL, NULL, NULL, "1064 ** You have an error in your SQL syntax; check the manual that correspon...")
#7 /var/www/html/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /var/www/html/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#9 /var/www/html/sites/all/modules/civicrm/packages/DB/DataObject.php(2438): DB_common->query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#10 /var/www/html/sites/all/modules/civicrm/packages/DB/DataObject.php(1627): DB_DataObject->_query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#11 /var/www/html/sites/all/modules/civicrm/CRM/Core/DAO.php(334): DB_DataObject->query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#12 /var/www/html/sites/all/modules/civicrm/CRM/Core/DAO.php(1267): CRM_Core_DAO->query("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", TRUE)
#13 /var/www/html/sites/all/modules/civicrm/CRM/Report/Form.php(2773): CRM_Core_DAO::executeQuery("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...")
#14 /var/www/html/sites/default/files/civicrm/custom_ext/ca.bidon.civiexportexcel/civiexportexcel.php(117): CRM_Report_Form->buildRows("SELECT civicrm_contact_assignee.sort_name as civicrm_contact_contact_assignee...", (Array:0))
#15 /var/www/html/sites/all/modules/civicrm/CRM/Utils/Hook.php(228): civiexportexcel_civicrm_buildForm("CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity))
#16 /var/www/html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:52), "civicrm_buildForm", 2, "CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity), NULL, NULL, NULL, NULL)
#17 /var/www/html/sites/all/modules/civicrm/CRM/Utils/Hook.php(384): CRM_Utils_Hook_DrupalBase->invoke(2, "CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity), NULL, NULL, NULL, NULL, "civicrm_buildForm")
#18 /var/www/html/sites/all/modules/civicrm/CRM/Core/Form.php(552): CRM_Utils_Hook::buildForm("CRM_Report_Form_Activity", Object(CRM_Report_Form_Activity))
#19 /var/www/html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Submit.php(61): CRM_Core_Form->buildForm()
#20 /var/www/html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Submit->perform(Object(CRM_Report_Form_Activity), "submit")
#21 /var/www/html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Report_Form_Activity), "submit")
#22 /var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("submit")
#23 /var/www/html/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(113): CRM_Core_Controller->run()
#24 /var/www/html/sites/all/modules/civicrm/CRM/Report/Page/Report.php(72): CRM_Utils_Wrapper->run("CRM_Report_Form_Activity", NULL, NULL)
#25 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Report_Page_Report->run((Array:3), NULL)
#26 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#27 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#28 /var/www/html/sites/all/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:3))
#29 [internal function](): civicrm_invoke("report", "activity")
#30 /var/www/html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#31 /var/www/html/index.php(21): menu_execute_active_handler()
#32 {main}
</pre>
